server {
    listen 80;

    # 1. Serwowanie frontendu (plików z folderu ./frontend)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Reverse Proxy dla FastAPI (Wszystkie zapytania na /api/ idą do kontenera Pythona)
    location /api/ {
        proxy_pass http://backend:8000/; # Upewnij się, że FastAPI nasłuchuje wewn. na 8000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Kluczowe dla Server-Sent Events (SSE) dla LangChaina
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }

    # 3. Reverse Proxy dla GeoServera (Wszystkie zapytania na /geoserver/ idą do k. GeoServera)
    location /geoserver/ {
        proxy_pass http://geoserver:8080/geoserver/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}