server {
    listen 80;

    # 1. Reverse Proxy dla środowiska deweloperskiego Vue (Vite)
    location / {
        proxy_pass http://vue_frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Konfiguracja WebSocketów dla Vite HMR (Hot Module Replacement)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # 2. Reverse Proxy dla FastAPI (Wszystkie zapytania na /api/ idą do kontenera Pythona)
    location /api/ {
        proxy_pass http://fastapi_backend:8000/; # Zmiana na nazwę usługi - poprawa stabilności połączenia
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Kluczowe dla Server-Sent Events (SSE) dla LangChaina
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }

    # 3. Reverse Proxy dla GeoServera (Wszystkie zapytania na /geoserver/ idą do k. GeoServera)
    location /geoserver/ {
        proxy_pass http://geoserver:8080/geoserver/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}